[build]
  command = "npm install && cd packages/taiko && npm run doc:api && npx eleventy"
  publish = "packages/taiko/docs/_site"

[[redirects]]
  from = "/devices"
  to = "https://github.com/getgauge/taiko/blob/master/packages/taiko/lib/data/devices.js"
