[build]
  command = "npm run doc"
  publish = "docs/_site"
[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/devices"
  to = "https://github.com/getgauge/taiko/blob/master/lib/data/devices.js"
