name: Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  release-and-bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'ReleaseCandidate')
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
      CI: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm install
        run: |
          npm install

      - name: Setup git
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Install hub
        run: brew install hub

      - name: Deploy on github
        run: |
          version=$(grep '"version"' package.json | sed 's/"version":[[:space:]]*"//' | sed 's/",//' | tr -d [:space:])
          if [ -z "$version" ]; then
              echo "Taiko version is not set"
              exit 1
          fi
          echo -e "taiko v$version\n\n" > desc.txt
          release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" taiko getgauge)
          echo "$release_description" >> desc.txt
          echo "Creating new draft for release v$version"
          hub release create -F ./desc.txt "v$version"
          rm -rf desc.txt

      - name: Deploy npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access=public

      - name: Bump up version
        env:
          GAUGE_CI_TOKEN: '${{ secrets.GAUGE_CI_TOKEN }}'
        run: |
          git checkout master git checkout . && git pull --rebase
          version=$(npm version patch --no-git-tag-version)
          git commit -am "Bumping up -> $version"
          git push "https://$GITHUB_ACTOR:$GAUGE_CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
