name: taiko

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests - ${{ matrix.os }} - ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20']
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: install
        run: npm install
      - name: install browser dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y  libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libcups2 \
            libxrandr2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libdrm-dev \
            libgbm-dev \
            libasound-dev
      - name: unit-tests
        run: |
          npm run lint:check
          npm test

  functional-tests:
    needs: unit-tests
    name: FTs - NodeJS ${{ matrix.node_version }} & ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20']
        os: [ubuntu-latest]
        include:
          - os: windows-latest
            node_version: '16'
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: install browser dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libcups2 \
            libxrandr2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libdrm-dev \
            libgbm-dev \
            libasound-dev
      - name: functional-tests
        run: npm run test-functional

      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/reports/html-report

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/logs

  functional-tests-headful:
    needs: unit-tests
    name: FT in linux-headful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: install browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libnss3 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libxcomposite1 \
              libcups2 \
              libxrandr2 \
              libpangocairo-1.0-0 \
              libgtk-3-0 \
              libdrm-dev \
              libgbm-dev \
              libasound-dev
      - name: install xvfb
        run: sudo apt install xvfb
      - name: functional-tests-headful
        env:
          headless: false
          TAIKO_HIGHLIGHT_ON_ACTION: false
        run: xvfb-run npm run test-functional
      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-linux-headful
          path: test/functional-tests/reports/html-report
      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-linux-headful
          path: test/functional-tests/logs

  docs-tests:
    needs: unit-tests
    name: Docs tests - ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 20
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: install
        run: npm install
      - name: install browser dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libcups2 \
            libxrandr2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libdrm-dev \
            libgbm-dev \
            libasound-dev
      - name: test-docs
        run: npm run test-docs
      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: docs-tests-reports-${{ matrix.os }}
          path: test/docs-tests/gauge/reports/html-report
      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: docs-tests-logs-${{ matrix.os }}
          path: test/docs-tests/gauge/logs
