name: taiko

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install
        run: npm install
      - name: unit-tests
        run: npm test

  functional-tests:
    needs: unit-tests
    name: FTs - NodeJS ${{ matrix.node_version }} & ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: functional-tests
        run: npm run test-functional

      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/reports/html-report

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/logs

  functional-tests-headful:
    needs: unit-tests
    name: FT in linux-headful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install xvfb
        run: sudo apt install xvfb
      - name: functional-tests-headful
        env:
          headless: false
        run: xvfb-run npm run test-functional
      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-linux-headful
          path: test/functional-tests/reports/html-report        
      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-linux-headful
          path: test/functional-tests/logs

