name: update-chrome
on:
  schedule:
    # cron job that will run 1st of every month by 12am
    - cron: '0 12 1 * *'

jobs:
  update-to-latest-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup
        run: |
          sudo apt-get update
           sudo apt-get install -y  libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libcups2 \
            libxrandr2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libdrm-dev \
            libgbm-dev \
            libasound-dev

      - name: Get Chrome version and update
        run: |
          npm install
          node scripts/updateChrome.ts
          revision=$(cat package.json | grep revision | awk '{print $2}' | sed 's/[",]//g')
          echo "REVISION=$revision" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GAUGEBOT_GITHUB_TOKEN }}
          branch: ${{format('{0}{1}', 'update-chrome-', env.REVISION)}}
          commit-message: ${{format('{0}{1}', 'Update chrome to revision ', env.REVISION)}}
          title: ${{format('{0}{1}', 'Update chrome to revision ', env.REVISION)}}
